# ██╗    ██╗██╗███╗   ██╗██████╗  ██████╗ ██╗    ██╗██████╗ ██╗   ██╗██╗     ███████╗
# ██║    ██║██║████╗  ██║██╔══██╗██╔═══██╗██║    ██║██╔══██╗██║   ██║██║     ██╔════╝
# ██║ █╗ ██║██║██╔██╗ ██║██║  ██║██║   ██║██║ █╗ ██║██████╔╝██║   ██║██║     █████╗  
# ██║███╗██║██║██║╚██╗██║██║  ██║██║   ██║██║███╗██║██╔══██╗██║   ██║██║     ██╔══╝  
# ╚███╔███╔╝██║██║ ╚████║██████╔╝╚██████╔╝╚███╔███╔╝██║  ██║╚██████╔╝███████╗███████╗
#  ╚══╝╚══╝ ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝  ╚══╝╚══╝ ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚══════╝
#------------------------------------------------------------------------------------

# Ignore maximize requests from apps
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0

# Disable blur for floating XWayland windows
windowrule = no_blur on, match:xwayland 1, match:float 1

# Set opacity for Thunar file manager
windowrule = opacity 0.85 0.85, match:class ^(thunar)$

windowrule = size 1600 900, match:class ^(firefox)$

# PacketTracer WindowRules

# Global for PacketTracer

# Fix drag and drop on XWayland

windowrule = no_initial_focus on, match:class PacketTracer

# windowrule = float on, match:class PacketTracer

windowrule = no_anim on, match:class PacketTracer

windowrule = no_blur on, match:class PacketTracer

windowrule = no_dim on, match:class PacketTracer

windowrule = no_shadow on, match:class PacketTracer

windowrule = opaque on, match:class PacketTracer

windowrule = immediate on, match:class PacketTracer

windowrule = border_size 0, match:class PacketTracer

windowrule = rounding 0, match:class PacketTracer

windowrule = decorate 0, match:class PacketTracer

windowrule = nearest_neighbor on, match:class PacketTracer

windowrule = xray on, match:class PacketTracer

windowrule = min_size 1 1, match:class PacketTracer

windowrule = keep_aspect_ratio on, match:class PacketTracer, match:title Cisco Packet Tracer

windowrule = focus_on_activate on, match:class PacketTracer, match:title Cisco Packet Tracer

# windowrule = stayfocused, match:class PacketTracer, match:title Preference

windowrule = min_size 486 628, match:class PacketTracer, match:title Preference

windowrule = min_size 486 628, match:class PacketTracer, match:title .*outer.*

windowrule = min_size 772 700, match:class PacketTracer, match:title .*witch.*

windowrule = min_size 807 655, match:class PacketTracer, match:title .*PC.*

windowrule = min_size 791 648, match:class PacketTracer, match:title .*Save File.
